apiVersion: v1
entries:
  centos-simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-23T15:50:09.630087153-04:00"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: 82f96f43bd2b47a9e48653b049fc99490bd4309b64e8e04eedeb288a585cf1d6
    icon: https://avatars.githubusercontent.com/u/55542927
    name: centos-simple-kmod
    type: application
    urls:
    - file:///charts/example/centos-simple-kmod-0.0.1.tgz
    version: 0.0.1
  driver-container-base:
  - annotations:
      appVersion: '>= 1.13.0 < 1.15.0'
    apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-23T15:50:09.630301954-04:00"
    description: Driver Container Base is the base image for out-of-tree builds
    digest: 274057e76b6d74c8d8b482f79cc0b6e8f6a9a7a8fdae9542d8a1e24000a06236
    icon: https://avatars.githubusercontent.com/u/55542927
    name: driver-container-base
    type: application
    urls:
    - file:///charts/example/driver-container-base-0.1.0.tgz
    version: 0.1.0
  ping-pong:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-23T15:50:09.630482824-04:00"
    description: Simple go app to showcase cert-manager intergration
    digest: 7da0f37862dfb60aa8ab4365bc78b56c5b69ca2df9a36192898c79b660ff5878
    icon: https://avatars.githubusercontent.com/u/55542927
    name: ping-pong
    type: application
    urls:
    - file:///charts/example/ping-pong-0.0.1.tgz
    version: 0.0.1
  simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-23T15:50:09.630627447-04:00"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: 4807b428951229568547939323986405f3bc498260978b72d9574a619462e9d1
    icon: https://avatars.githubusercontent.com/u/55542927
    name: simple-kmod
    type: application
    urls:
    - file:///charts/example/simple-kmod-0.0.1.tgz
    version: 0.0.1
generated: "2021-06-23T15:50:09.629811784-04:00"
