apiVersion: v1
entries:
  centos-simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-28T13:05:13.382090427-04:00"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: 70d5ccdaa7a79280d9615cab8966d3b5e2f32612f96e59f41aa54f621ed6abaf
    icon: https://avatars.githubusercontent.com/u/55542927
    name: centos-simple-kmod
    type: application
    urls:
    - file:///charts/example/centos-simple-kmod-0.0.1.tgz
    version: 0.0.1
  driver-container-base:
  - annotations:
      appVersion: '>= 1.13.0 < 1.15.0'
    apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-28T13:05:13.382336713-04:00"
    description: Driver Container Base is the base image for out-of-tree builds
    digest: 274057e76b6d74c8d8b482f79cc0b6e8f6a9a7a8fdae9542d8a1e24000a06236
    icon: https://avatars.githubusercontent.com/u/55542927
    name: driver-container-base
    type: application
    urls:
    - file:///charts/example/driver-container-base-0.1.0.tgz
    version: 0.1.0
  ping-pong:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-28T13:05:13.382610241-04:00"
    description: Simple go app to showcase cert-manager intergration
    digest: b3646bb435472c73bc5166cdbc3ec83b512d175c7283298e5f182a777849b3c7
    icon: https://avatars.githubusercontent.com/u/55542927
    name: ping-pong
    type: application
    urls:
    - file:///charts/example/ping-pong-0.0.1.tgz
    version: 0.0.1
  simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-28T13:05:13.382759499-04:00"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: f2dc9fc28a0e15d36e432589920474da28049f7329e808c0345312ff4c02df1b
    icon: https://avatars.githubusercontent.com/u/55542927
    name: simple-kmod
    type: application
    urls:
    - file:///charts/example/simple-kmod-0.0.1.tgz
    version: 0.0.1
generated: "2021-06-28T13:05:13.381214175-04:00"
