apiVersion: v1
entries:
  centos-centos-simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-17T15:06:53.103451035-04:00"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: 94619a263900939def63a1c771603c666458fa0161394616a26ce503c085f22f
    icon: https://avatars.githubusercontent.com/u/55542927
    name: centos-centos-simple-kmod
    type: application
    urls:
    - file:///charts/example/centos-centos-simple-kmod-0.0.1.tgz
    version: 0.0.1
  centos-simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-17T15:06:53.103614223-04:00"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: fee514e369cb7868fc42c6906f25c564de453144a5cfac8cd90d4a32d34d6ec2
    icon: https://avatars.githubusercontent.com/u/55542927
    name: centos-simple-kmod
    type: application
    urls:
    - file:///charts/example/centos-simple-kmod-0.0.1.tgz
    version: 0.0.1
  driver-container-base:
  - annotations:
      appVersion: '>= 1.13.0 < 1.15.0'
    apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-17T15:06:53.103797645-04:00"
    description: Driver Container Base is the base image for out-of-tree builds
    digest: 274057e76b6d74c8d8b482f79cc0b6e8f6a9a7a8fdae9542d8a1e24000a06236
    icon: https://avatars.githubusercontent.com/u/55542927
    name: driver-container-base
    type: application
    urls:
    - file:///charts/example/driver-container-base-0.1.0.tgz
    version: 0.1.0
  ping-pong:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-17T15:06:53.103959553-04:00"
    description: Simple go app to showcase cert-manager intergration
    digest: 99cb3c88397090e5fa61e13f7809c6a3d2180acf2b56949e588d759befd63786
    icon: https://avatars.githubusercontent.com/u/55542927
    name: ping-pong
    type: application
    urls:
    - file:///charts/example/ping-pong-0.0.1.tgz
    version: 0.0.1
  simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-17T15:06:53.104093343-04:00"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: d365be60f582c93cda4bd50f10d0834519c6473b2a84b9526078b39f49be397b
    icon: https://avatars.githubusercontent.com/u/55542927
    name: simple-kmod
    type: application
    urls:
    - file:///charts/example/simple-kmod-0.0.1.tgz
    version: 0.0.1
generated: "2021-06-17T15:06:53.103174047-04:00"
